# Dependencies
markdown:         kramdown #redcarpet
highlighter:      rouge  #pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            All things
tagline:          'Deep Learning'
description:      'Cloud, Data, Machine Learning, and more.'
url:              https://dzlab.github.io
baseurl:          /

author:
  name:           'dzlab'
  twitter:        https://twitter.com/bachiirc

paginate:         10

google_analytics: UA-128961990-1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dzlab

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-toc
  - jekyll-paginate
  - jekyll-sitemap

kramdown:
  parse_block_html: true
